name: Publish and Release

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 18

jobs:
  release:
    runs-on: windows-latest
    name: Publish and Release
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - name: Prepare
        shell: bash
        run: |
          npm ci
          npm test
      - name: Publish and Release
        uses: akashic-games/action-release@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          npm_token: ${{ secrets.NPM_TOKEN }}
      - name: Upload Runtime Zip to Release Note
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          node scripts/release.js
